### ISSUE TITLE
Share benchmarks

### ISSUE THREAD

**Issue by dtolnay** [gamache/jsonxf#1]
Please publish the benchmarking code/commands as well as a script to generate the input files you used. Thanks!

**Comment by gamache** [comment]
Hi David!  I'll update the README to this effect, but essentially the commands I used to benchmark were all of the form:

    time (command <input.json >output.json)

Each time shown in the README is the average of the `real` time from three consecutive runs.  Nothing too scientific, but enough to show trends.

I can't share the exact data that I used, but I'll work on putting together a benchmark around some public JSON data.

**Comment by dtolnay** [comment]
Nice, thank you. The twitter1410.json from #2 would be about the right size.

**Comment by gamache** [comment]
Resolved with [0.7.0](https://github.com/gamache/jsonxf/releases/tag/0.7.0)!
