### ISSUE TITLE
Benchmark against serde_json

### ISSUE THREAD

**Issue by dtolnay** [gamache/jsonxf#2]
I would be interested to see this comparison. Jsonxf does less work (no input validation, does not parse the value of numbers, etc) so I would expect it to be measurably faster.

I tried comparing 850MB made of 1410 copies of [`twitter.json`](https://github.com/serde-rs/json-benchmark/blob/master/data/twitter.json) between jsonxf and a basic serde_json pretty printer based on [this example code](https://serde.rs/transcode.html).

```
cat twitter.json twitter.json twitter.json twitter.json twitter.json twitter.json > twitter6.json
cat twitter6.json twitter6.json twitter6.json twitter6.json twitter6.json twitter6.json > twitter36.json
cat twitter36.json  twitter36.json twitter36.json twitter36.json twitter36.json twitter36.json > twitter216.json
cat twitter216.json  twitter216.json twitter216.json twitter216.json twitter216.json twitter216.json > twitter1296.json
cat twitter1296.json twitter36.json twitter36.json twitter36.json twitter6.json > twitter1410.json
```

```rust
extern crate serde_json;
extern crate serde_transcode;

use std::io::{self, Read, Write};

fn main() {
    let stdin = io::stdin();
    let stdout = io::stdout();

    let mut input = String::new();
    stdin.lock().read_to_string(&mut input).unwrap();
    let mut output = Vec::with_capacity(input.len());

    {
        let mut d = serde_json::Deserializer::from_str(&input);
        let mut s = serde_json::Serializer::pretty(&mut output);
        while serde_transcode::transcode(&mut d, &mut s).is_ok() {}
    }

    stdout.lock().write_all(&output).unwrap();
}
```

On my machine I get the following times, with Serde about 2.5x faster.

```
$ time target/release/serdexf <twitter1410.json >/dev/null
real	0m5.483s
user	0m4.204s
sys	0m1.276s

$ time target/release/jsonxf <twitter1410.json >/dev/null
real	0m14.115s
user	0m13.972s
sys	0m0.140s
```

**Comment by dtolnay** [comment]
And for minimizing I get a 2.7x difference (change "pretty" to "new" in the Serde code).

```
$ time target/release/serdexf <twitter1410.json >/dev/null
real	0m4.772s
user	0m3.712s
sys	0m1.060s

$ time target/release/jsonxf -m <twitter1410.json >/dev/null
real	0m12.959s
user	0m12.808s
sys	0m0.148s
```

**Comment by gamache** [comment]
I am seeing the same thing -- serde is beating jsonxf every time, though not quite as badly as shown here if you write output to a file rather than `/dev/null`.  I'm seeing ~9s for serde vs ~15.5 seconds for jsonxf in the pretty-print test.  Time to figure out how serde got so fast!

**Comment by dtolnay** [comment]
I updated the code shortly after I opened the issue to write to memory first and then write to stdout all at once, to match more closely what jsonxf::pretty_print does. That was faster than writing fragments at a time to the output so check that you grabbed that version.

I am excited to see what you find. 😆 Hopefully it is a few easy changes and you get a 3-5x speedup in jsonxf and beat jsonpp+jq even better.

**Comment by gamache** [comment]
Not as drastic as 3-5x, but I've done a bit of work and Jsonxf is now beating the serde code by 10-30%.  I've updated the README to show the new benchmark results, and I've also added a `benchmark/` directory containing the script I'm using to run these benchmarks now.  Thanks for opening these issues, the code is better for it now!
