### ISSUE TITLE
when comman option -i -o use a identical file path, output is none

### ISSUE THREAD

**Issue by anthhub** [gamache/jsonxf#5]
For Example:

``` shell
jsonxf -i 1.json -o 1.json
```

1.json content will be lost

**Comment by gamache** [comment]
Hi @anthhub! Thank you for the report. I'll try and fix this soon.

**Comment by anthhub** [comment]
Thank you very much!

It did solve my problem!

**Comment by anthhub** [comment]
I made a VScode plugin using jsonxf 😁: https://marketplace.visualstudio.com/items?itemName=anthhub.fat-json
